version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: jugnu670
      MYSQL_DATABASE: jugnu
      MYSQL_USER: jugnu
      MYSQL_PASSWORD: jugnu670
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    depends_on: 
      - mysql
    links:
      - mysql:mysql
    build: .
    restart: always
    ports:
      - "80:80"
      - "5000:5000"

volumes:
  mysql_data:
